export interface GossipMessage {
  /** Unique message ID — UUID generated by originator */
  id: string;
  /** Original message type (auction.started, bid.submit, etc.) */
  type: string;
  /** Message payload */
  payload: unknown;
  /** Originator node ID */
  origin: string;
  /** Hop count (incremented each relay) */
  hops: number;
  /** Timestamp (epoch ms) when originally created */
  ts: number;
}

export interface GossipConfig {
  /** Max messages to track for dedup. Default 10000. */
  maxSeenSize?: number;
  /** Max age (ms) for seen messages before eviction. Default 120000 (2 min). */
  seenTtlMs?: number;
  /** Max hop count before dropping. Default 10. */
  maxHops?: number;
}

const PRUNE_INTERVAL_MS = 30_000;

export class GossipProtocol {
  private seen = new Map<string, number>();
  private config: Required<GossipConfig>;
  private myNodeId: string;
  private pruneTimer: ReturnType<typeof setInterval> | null = null;

  constructor(nodeId: string, config?: GossipConfig) {
    this.myNodeId = nodeId;
    this.config = {
      maxSeenSize: config?.maxSeenSize ?? 10_000,
      seenTtlMs: config?.seenTtlMs ?? 120_000,
      maxHops: config?.maxHops ?? 10,
    };
    this.pruneTimer = setInterval(() => this.prune(), PRUNE_INTERVAL_MS);
  }

  createMessage(type: string, payload: unknown): GossipMessage {
    const id =
      typeof crypto !== 'undefined' && 'randomUUID' in crypto
        ? crypto.randomUUID()
        : `${Math.random().toString(36).slice(2)}${Date.now()}`;

    const msg: GossipMessage = {
      id,
      type,
      payload,
      origin: this.myNodeId,
      hops: 0,
      ts: Date.now(),
    };
    this.seen.set(id, Date.now());
    return msg;
  }

  processIncoming(raw: string): GossipMessage | null {
    let msg: GossipMessage;
    try {
      msg = JSON.parse(raw) as GossipMessage;
    } catch {
      return null;
    }

    if (!msg.id || !msg.type) return null;
    if (this.seen.has(msg.id)) return null;
    if (msg.hops >= this.config.maxHops) return null;

    const age = Date.now() - msg.ts;
    if (age > this.config.seenTtlMs) return null;

    this.seen.set(msg.id, Date.now());
    msg.hops++;
    return msg;
  }

  serialize(msg: GossipMessage): string {
    return JSON.stringify(msg);
  }

  prune(): void {
    const now = Date.now();
    for (const [id, ts] of this.seen) {
      if (now - ts > this.config.seenTtlMs) {
        this.seen.delete(id);
      }
    }
    // If still over limit, delete oldest
    if (this.seen.size > this.config.maxSeenSize) {
      const entries = [...this.seen.entries()].sort((a, b) => a[1] - b[1]);
      const toDelete = entries.slice(
        0,
        this.seen.size - this.config.maxSeenSize
      );
      for (const [id] of toDelete) {
        this.seen.delete(id);
      }
    }
  }

  destroy(): void {
    if (this.pruneTimer) {
      clearInterval(this.pruneTimer);
      this.pruneTimer = null;
    }
  }
}
