# syntax=docker/dockerfile:1

# Multi-stage build. The backend services (api-service, api-worker, reconciler,
# relayer, market-keeper) share this one image and differ only by their ECS
# `command`. Two goals vs the old single-stage build:
#   1. Keep the apt build toolchain (g++/make/python3/-dev headers) OUT of the
#      final image — it's only needed to compile native modules at build time.
#   2. Install only the BACKEND dependency closure (api, relayer, market-keeper
#      + @sapience/sdk), skipping the frontend packages (app, ui, docs) and
#      their heavy deps (Next.js, etc.) that this image never runs.
# Dev dependencies ARE kept: the services run TypeScript directly via `tsx`, and
# the api boot sequence runs `prisma migrate deploy` + `graphql-codegen` — all of
# which live in devDependencies, so a `--prod` prune would break startup.

# ── Builder ───────────────────────────────────────────────────────────
FROM node:22-slim AS builder

RUN corepack enable && corepack prepare pnpm@10.33.4 --activate

# Native module build deps (usb, node-hid, secp256k1) + openssl for Prisma.
RUN apt-get update && apt-get install -y \
 openssl \
 python3 \
 make \
 g++ \
 libusb-1.0-0-dev \
 libudev-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Workspace config (for dependency resolution layer caching)
COPY .npmrc pnpm-workspace.yaml pnpm-lock.yaml package.json ./

# ALL package manifests — `--frozen-lockfile` validates the full workspace graph
# against the lockfile, so every manifest must be present even though we only
# install the backend closure below.
COPY packages/sdk/package.json packages/sdk/
COPY packages/api/package.json packages/api/
COPY packages/api/prisma/ packages/api/prisma/
COPY packages/app/package.json packages/app/
COPY packages/relayer/package.json packages/relayer/
COPY packages/ui/package.json packages/ui/
COPY packages/protocol/package.json packages/protocol/
COPY packages/docs/package.json packages/docs/
COPY packages/edge-cache/package.json packages/edge-cache/
COPY packages/market-keeper/package.json packages/market-keeper/

# Install ONLY the backend closure. `<pkg>...` selects the package plus its
# (workspace) dependencies, so @sapience/sdk comes along; app/ui/docs and their
# deps are skipped. Frontend npm deps (Next.js, etc.) never enter the store.
ENV BACKEND_FILTER="--filter @sapience/api... --filter @sapience/relayer... --filter @sapience/market-keeper..."
RUN pnpm install --frozen-lockfile --ignore-scripts $BACKEND_FILTER

# Run postinstall scripts that set up native binaries (skip prepare hooks)
RUN pnpm rebuild

# Build SDK (required by other packages at runtime)
COPY packages/sdk/ packages/sdk/
RUN pnpm --filter @sapience/sdk run build:lib

# Backend source only (app/ui/docs/protocol are not run in this image)
COPY packages/api/ packages/api/
COPY packages/relayer/ packages/relayer/
COPY packages/market-keeper/ packages/market-keeper/

# Re-run install with scripts now that all source is present. Prisma 7 ships
# its CLI as build/index.js generated by a postinstall step that we previously
# skipped with --ignore-scripts; the prepare hooks (which build the SDK) are
# now safe to run because the SDK source has been copied above.
RUN pnpm install --frozen-lockfile --offline $BACKEND_FILTER

# Generate Prisma client
RUN pnpm --filter @sapience/api run prisma:generate

# Compile market-keeper scripts for the cron runtime and fail the image build
# if the start script's first target is missing.
RUN pnpm --filter @sapience/market-keeper run build \
 && test -f packages/market-keeper/dist/scripts/refresh-metadata.js

# ── Runtime ───────────────────────────────────────────────────────────
FROM node:22-slim AS runtime

RUN corepack enable && corepack prepare pnpm@10.33.4 --activate

# RUNTIME shared libraries only — NO compilers or -dev headers. openssl for
# Prisma; libusb-1.0-0 + libudev1 for the native usb/node-hid modules whose
# compiled .node binaries are copied in from the builder.
RUN apt-get update && apt-get install -y \
 openssl \
 libusb-1.0-0 \
 libudev1 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# The fully-built backend workspace: node_modules (with compiled native
# binaries + generated Prisma client) + source + market-keeper dist.
COPY --from=builder /app /app

# Runtime default; deployment environments can override this (e.g. staging).
ENV NODE_ENV=production
