FROM node:22-slim

RUN corepack enable && corepack prepare pnpm@10.33.4 --activate

# Native module build deps (usb, node-hid, secp256k1) + openssl for Prisma
RUN apt-get update && apt-get install -y \
 openssl \
 python3 \
 make \
 g++ \
 libusb-1.0-0-dev \
 libudev-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Workspace config (for dependency resolution layer caching)
COPY .npmrc pnpm-workspace.yaml pnpm-lock.yaml package.json ./

# Package manifests
COPY packages/sdk/package.json packages/sdk/
COPY packages/api/package.json packages/api/
COPY packages/api/prisma/ packages/api/prisma/
COPY packages/app/package.json packages/app/
COPY packages/relayer/package.json packages/relayer/
COPY packages/ui/package.json packages/ui/
COPY packages/protocol/package.json packages/protocol/
COPY packages/docs/package.json packages/docs/
COPY packages/edge-cache/package.json packages/edge-cache/
COPY packages/market-keeper/package.json packages/market-keeper/

RUN pnpm install --frozen-lockfile --ignore-scripts

# Run postinstall scripts that set up native binaries (skip prepare hooks)
RUN pnpm rebuild

# Build SDK (required by other packages at runtime)
COPY packages/sdk/ packages/sdk/
RUN pnpm --filter @sapience/sdk run build:lib

# Copy remaining source
COPY packages/ packages/

# Re-run install with scripts now that all source is present. Prisma 7 ships
# its CLI as build/index.js generated by a postinstall step that we previously
# skipped with --ignore-scripts; the prepare hooks (which build the SDK) are
# now safe to run because the SDK source has been copied above.
RUN pnpm install --frozen-lockfile --offline

# Generate Prisma client
RUN pnpm --filter @sapience/api run prisma:generate

# Compile market-keeper scripts for the cron runtime and fail the image build
# if the start script's first target is missing.
RUN pnpm --filter @sapience/market-keeper run build \
 && test -f packages/market-keeper/dist/scripts/refresh-metadata.js

# Runtime default; deployment environments can override this (e.g. staging).
ENV NODE_ENV=production
