/**
 * Golden Hash Tests for escrowSigning.ts
 *
 * These tests ensure the TypeScript hash computations match the Solidity contract.
 * They catch:
 *   - Missing fields in hash computation (e.g. #1153 sponsor field)
 *   - Wrong encoding order or types
 *   - Accidental field removal during refactors
 *
 * The "golden values" are computed inline using viem's hashTypedData —
 * the same EIP-712 spec implementation that OpenZeppelin uses.
 * If the SDK functions drift from the spec, these tests break.
 */

import { describe, test, expect } from 'vitest';
import {
  type Address,
  type Hex,
  encodeAbiParameters,
  getAddress,
  hashTypedData,
  keccak256,
  toHex,
  zeroAddress,
} from 'viem';

import {
  computePredictionHash,
  computePredictionHashFromPicks,
  computeBurnHash,
  buildMintApprovalTypedData,
  buildBurnApprovalTypedData,
  buildPredictorMintTypedData,
  buildCounterpartyMintTypedData,
  buildAuctionIntentTypedData,
  hashMintApproval,
  hashBurnApproval,
  getEscrowDomain,
  MINT_APPROVAL_TYPES,
  BURN_APPROVAL_TYPES,
} from './escrowSigning';

import {
  computePickConfigId,
  computePredictionId,
  canonicalizePicks,
} from './escrowEncoding';

import type { Pick } from '../types/escrow';

// Golden values generated by: forge script test/v2/fixtures/GenerateHashFixtures.s.sol -vvv
// These come from the REAL Solidity contract. If the SDK disagrees, we have a bug.
import goldenHashes from './__fixtures__/escrowHashes.json';

// ============================================================================
// Test Fixtures
// ============================================================================

const PREDICTOR = getAddress('0x1111111111111111111111111111111111111111');
const COUNTERPARTY = getAddress('0x2222222222222222222222222222222222222222');
const ESCROW_CONTRACT = getAddress(
  '0x3333333333333333333333333333333333333333'
);
const SPONSOR = getAddress('0x4444444444444444444444444444444444444444');
const CHAIN_ID = 13374202; // Ethereal testnet

const RESOLVER_A = getAddress('0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa');
const RESOLVER_B = getAddress('0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB');

// Note: predictedOutcome maps to OutcomeSide enum in Solidity:
// YES = 0, NO = 1. If the enum order ever changes, these fixtures and
// the Forge script (GenerateHashFixtures.s.sol) must both be updated.
const PICKS: Pick[] = [
  {
    conditionResolver: RESOLVER_A,
    conditionId: ('0x' + 'ab'.repeat(32)) as Hex,
    predictedOutcome: 1, // OutcomeSide.NO
  },
];

const TWO_PICKS: Pick[] = [
  {
    conditionResolver: RESOLVER_A,
    conditionId: ('0x' + 'ab'.repeat(32)) as Hex,
    predictedOutcome: 1,
  },
  {
    conditionResolver: RESOLVER_B,
    conditionId: ('0x' + 'cd'.repeat(32)) as Hex,
    predictedOutcome: 0,
  },
];

const PREDICTOR_COLLATERAL = 1000000n;
const COUNTERPARTY_COLLATERAL = 1000000n;
const NONCE = 42n;
const DEADLINE = 1700000000n;

// ============================================================================
// 0. Cross-language golden hash tests (Solidity ↔ TypeScript)
// ============================================================================

describe('cross-language: SDK matches Solidity contract', () => {
  test('pickConfigId (single pick)', () => {
    const sdkResult = computePickConfigId(PICKS);
    expect(sdkResult).toBe(goldenHashes.pickConfigId);
  });

  test('pickConfigId (two picks)', () => {
    const sdkResult = computePickConfigId(TWO_PICKS);
    expect(sdkResult).toBe(goldenHashes.twoPickConfigId);
  });

  test('predictionHash without sponsor', () => {
    const pickConfigId = computePickConfigId(PICKS);
    const sdkResult = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );
    expect(sdkResult).toBe(goldenHashes.predictionHashNoSponsor);
  });

  test('predictionHash with sponsor (catches #1153)', () => {
    const pickConfigId = computePickConfigId(PICKS);
    const sdkResult = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      SPONSOR,
      '0x'
    );
    expect(sdkResult).toBe(goldenHashes.predictionHashWithSponsor);
  });

  test('predictionHash with sponsor + data', () => {
    const pickConfigId = computePickConfigId(PICKS);
    const sdkResult = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      SPONSOR,
      '0x1234'
    );
    expect(sdkResult).toBe(goldenHashes.predictionHashWithSponsorData);
  });

  test('burnHash', () => {
    const pickConfigId = computePickConfigId(PICKS);
    const sdkResult = computeBurnHash(
      pickConfigId,
      500000n,
      500000n,
      PREDICTOR,
      COUNTERPARTY,
      1000000n,
      0n
    );
    expect(sdkResult).toBe(goldenHashes.burnHash);
  });

  test('MintApproval struct hash matches contract typehash', () => {
    const predictionHash = goldenHashes.predictionHashNoSponsor as Hex;
    // Compute the struct hash the same way the contract does:
    // keccak256(abi.encode(TYPEHASH, predictionHash, signer, collateral, nonce, deadline))
    const sdkStructHash = keccak256(
      encodeAbiParameters(
        [
          { type: 'bytes32' }, // typehash
          { type: 'bytes32' }, // predictionHash
          { type: 'address' }, // signer
          { type: 'uint256' }, // collateral
          { type: 'uint256' }, // nonce
          { type: 'uint256' }, // deadline
        ],
        [
          // This string MUST match SignatureValidator.MINT_APPROVAL_TYPEHASH
          keccak256(
            toHex(
              'MintApproval(bytes32 predictionHash,address signer,uint256 collateral,uint256 nonce,uint256 deadline)'
            )
          ),
          predictionHash,
          PREDICTOR,
          PREDICTOR_COLLATERAL,
          NONCE,
          DEADLINE,
        ]
      )
    );
    expect(sdkStructHash).toBe(goldenHashes.mintApprovalStructHash);
  });

  test('BurnApproval struct hash matches contract typehash', () => {
    const burnHashValue = goldenHashes.burnHash as Hex;
    const sdkStructHash = keccak256(
      encodeAbiParameters(
        [
          { type: 'bytes32' },
          { type: 'bytes32' },
          { type: 'address' },
          { type: 'uint256' },
          { type: 'uint256' },
          { type: 'uint256' },
          { type: 'uint256' },
        ],
        [
          keccak256(
            toHex(
              'BurnApproval(bytes32 burnHash,address signer,uint256 tokenAmount,uint256 payout,uint256 nonce,uint256 deadline)'
            )
          ),
          burnHashValue,
          PREDICTOR,
          500000n,
          1000000n,
          NONCE,
          DEADLINE,
        ]
      )
    );
    expect(sdkStructHash).toBe(goldenHashes.burnApprovalStructHash);
  });
});

// ============================================================================
// 0b. Permission hashes (catches #1156: keccak256("V2_MINT") vs keccak256("MINT"))
// ============================================================================

describe('cross-language: permission constants', () => {
  test('MINT_PERMISSION matches contract keccak256("MINT")', () => {
    const sdkMintPermission = keccak256(toHex('MINT'));
    expect(sdkMintPermission).toBe(goldenHashes.mintPermission);
  });

  test('BURN_PERMISSION matches contract keccak256("BURN")', () => {
    const sdkBurnPermission = keccak256(toHex('BURN'));
    expect(sdkBurnPermission).toBe(goldenHashes.burnPermission);
  });

  test('MINT_PERMISSION is NOT keccak256("V2_MINT") (regression for #1156)', () => {
    const wrongPermission = keccak256(toHex('V2_MINT'));
    expect(wrongPermission).not.toBe(goldenHashes.mintPermission);
  });
});

// ============================================================================
// 0c. Full EIP-712 digest (_hashTypedDataV4) with domain separator
// ============================================================================

describe('cross-language: full EIP-712 digest with domain', () => {
  // The Forge fixture runs with chainId=31337 (Anvil default) and the
  // harness contract's deployed address. We reconstruct the same domain
  // to verify the SDK's hashMintApproval/hashBurnApproval produce
  // identical digests when given the same domain parameters.
  const fixtureChainId = goldenHashes.domainChainId;
  const fixtureContract = goldenHashes.domainVerifyingContract as Address;

  test('hashMintApproval matches contract _hashTypedDataV4', () => {
    const sdkDigest = hashMintApproval({
      predictionHash: goldenHashes.predictionHashNoSponsor as Hex,
      signer: PREDICTOR,
      collateral: PREDICTOR_COLLATERAL,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: fixtureContract,
      chainId: fixtureChainId,
    });
    expect(sdkDigest).toBe(goldenHashes.mintApprovalDigest);
  });

  test('hashBurnApproval matches contract _hashTypedDataV4', () => {
    const sdkDigest = hashBurnApproval({
      burnHash: goldenHashes.burnHash as Hex,
      signer: PREDICTOR,
      tokenAmount: 500000n,
      payout: 1000000n,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: fixtureContract,
      chainId: fixtureChainId,
    });
    expect(sdkDigest).toBe(goldenHashes.burnApprovalDigest);
  });

  test('different chainId produces different digest (domain drift)', () => {
    const digest1 = hashMintApproval({
      predictionHash: goldenHashes.predictionHashNoSponsor as Hex,
      signer: PREDICTOR,
      collateral: PREDICTOR_COLLATERAL,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: fixtureContract,
      chainId: fixtureChainId,
    });
    const digest2 = hashMintApproval({
      predictionHash: goldenHashes.predictionHashNoSponsor as Hex,
      signer: PREDICTOR,
      collateral: PREDICTOR_COLLATERAL,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: fixtureContract,
      chainId: 42161, // Arbitrum mainnet
    });
    expect(digest1).not.toBe(digest2);
  });

  test('different verifyingContract produces different digest (domain drift)', () => {
    const digest1 = hashMintApproval({
      predictionHash: goldenHashes.predictionHashNoSponsor as Hex,
      signer: PREDICTOR,
      collateral: PREDICTOR_COLLATERAL,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: fixtureContract,
      chainId: fixtureChainId,
    });
    const digest2 = hashMintApproval({
      predictionHash: goldenHashes.predictionHashNoSponsor as Hex,
      signer: PREDICTOR,
      collateral: PREDICTOR_COLLATERAL,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: getAddress(
        '0x5555555555555555555555555555555555555555'
      ),
      chainId: fixtureChainId,
    });
    expect(digest1).not.toBe(digest2);
  });

  test('domain name and version are correct', () => {
    const domain = getEscrowDomain(fixtureContract, fixtureChainId);
    expect(domain.name).toBe('PredictionMarketEscrow');
    expect(domain.version).toBe('1');
  });
});

// ============================================================================
// 1. predictionHash — field completeness
// ============================================================================

describe('computePredictionHash', () => {
  const pickConfigId = computePickConfigId(PICKS);

  test('includes all 7 fields in the hash', () => {
    // Compute the expected hash manually using the same encoding the contract uses:
    // keccak256(abi.encode(pickConfigId, predictorCollateral, counterpartyCollateral,
    //                      predictor, counterparty, predictorSponsor, predictorSponsorData))
    const expected = keccak256(
      encodeAbiParameters(
        [
          { type: 'bytes32' },
          { type: 'uint256' },
          { type: 'uint256' },
          { type: 'address' },
          { type: 'address' },
          { type: 'address' },
          { type: 'bytes' },
        ],
        [
          pickConfigId,
          PREDICTOR_COLLATERAL,
          COUNTERPARTY_COLLATERAL,
          PREDICTOR,
          COUNTERPARTY,
          zeroAddress,
          '0x',
        ]
      )
    );

    const actual = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );

    expect(actual).toBe(expected);
  });

  test('changing predictorSponsor changes the hash (catches #1153)', () => {
    const withoutSponsor = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );

    const withSponsor = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      SPONSOR,
      '0x'
    );

    expect(withoutSponsor).not.toBe(withSponsor);
  });

  test('changing predictorSponsorData changes the hash', () => {
    const withoutData = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      SPONSOR,
      '0x'
    );

    const withData = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      SPONSOR,
      '0x1234'
    );

    expect(withoutData).not.toBe(withData);
  });

  test('changing predictor changes the hash', () => {
    const hash1 = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );
    const hash2 = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      COUNTERPARTY,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );
    expect(hash1).not.toBe(hash2);
  });

  test('changing counterparty changes the hash', () => {
    const hash1 = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );
    const hash2 = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      PREDICTOR,
      zeroAddress,
      '0x'
    );
    expect(hash1).not.toBe(hash2);
  });

  test('changing collateral amounts changes the hash', () => {
    const hash1 = computePredictionHash(
      pickConfigId,
      1000000n,
      1000000n,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );
    const hash2 = computePredictionHash(
      pickConfigId,
      2000000n,
      1000000n,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );
    const hash3 = computePredictionHash(
      pickConfigId,
      1000000n,
      2000000n,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );
    expect(hash1).not.toBe(hash2);
    expect(hash1).not.toBe(hash3);
    expect(hash2).not.toBe(hash3);
  });

  test('computePredictionHashFromPicks matches computePredictionHash', () => {
    const fromPicks = computePredictionHashFromPicks(
      PICKS,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );
    const fromConfigId = computePredictionHash(
      pickConfigId,
      PREDICTOR_COLLATERAL,
      COUNTERPARTY_COLLATERAL,
      PREDICTOR,
      COUNTERPARTY,
      zeroAddress,
      '0x'
    );
    expect(fromPicks).toBe(fromConfigId);
  });
});

// ============================================================================
// 2. pickConfigId — canonical ordering
// ============================================================================

describe('computePickConfigId', () => {
  // Note: the contract does NOT canonicalize picks — it hashes them in the order
  // received. canonicalizePicks() is an SDK-side responsibility. These tests verify
  // that ordering affects the hash (so the caller must canonicalize before submitting).
  test('pick order matters (non-canonical order gives different configId)', () => {
    const forward = computePickConfigId(TWO_PICKS);
    const reversed = computePickConfigId([...TWO_PICKS].reverse());
    // Order matters! That's why canonicalizePicks exists
    expect(forward).not.toBe(reversed);
  });

  test('canonicalized picks always produce the same configId regardless of input order', () => {
    const canonical1 = computePickConfigId(canonicalizePicks(TWO_PICKS));
    const canonical2 = computePickConfigId(
      canonicalizePicks([...TWO_PICKS].reverse())
    );
    expect(canonical1).toBe(canonical2);
  });
});

// ============================================================================
// 3. burnHash — field completeness
// ============================================================================

describe('computeBurnHash', () => {
  const pickConfigId = computePickConfigId(PICKS);

  test('matches manual abi.encode computation', () => {
    const expected = keccak256(
      encodeAbiParameters(
        [
          { type: 'bytes32' },
          { type: 'uint256' },
          { type: 'uint256' },
          { type: 'address' },
          { type: 'address' },
          { type: 'uint256' },
          { type: 'uint256' },
        ],
        [pickConfigId, 500000n, 500000n, PREDICTOR, COUNTERPARTY, 1000000n, 0n]
      )
    );

    const actual = computeBurnHash(
      pickConfigId,
      500000n,
      500000n,
      PREDICTOR,
      COUNTERPARTY,
      1000000n,
      0n
    );

    expect(actual).toBe(expected);
  });

  test('changing any field changes the hash', () => {
    const base = computeBurnHash(
      pickConfigId,
      500000n,
      500000n,
      PREDICTOR,
      COUNTERPARTY,
      1000000n,
      0n
    );

    // Different token amounts
    expect(
      computeBurnHash(
        pickConfigId,
        600000n,
        500000n,
        PREDICTOR,
        COUNTERPARTY,
        1000000n,
        0n
      )
    ).not.toBe(base);
    // Different holders
    expect(
      computeBurnHash(
        pickConfigId,
        500000n,
        500000n,
        COUNTERPARTY,
        COUNTERPARTY,
        1000000n,
        0n
      )
    ).not.toBe(base);
    // Different payouts
    expect(
      computeBurnHash(
        pickConfigId,
        500000n,
        500000n,
        PREDICTOR,
        COUNTERPARTY,
        500000n,
        500000n
      )
    ).not.toBe(base);
  });
});

// ============================================================================
// 4. MintApproval EIP-712 typed data — structure & signer correctness
// ============================================================================

describe('buildMintApprovalTypedData', () => {
  const predictionHash = computePredictionHash(
    computePickConfigId(PICKS),
    PREDICTOR_COLLATERAL,
    COUNTERPARTY_COLLATERAL,
    PREDICTOR,
    COUNTERPARTY,
    zeroAddress,
    '0x'
  );

  test('domain matches contract config', () => {
    const typed = buildMintApprovalTypedData({
      predictionHash,
      signer: PREDICTOR,
      collateral: PREDICTOR_COLLATERAL,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    });

    expect(typed.domain.name).toBe('PredictionMarketEscrow');
    expect(typed.domain.version).toBe('1');
    expect(typed.domain.verifyingContract).toBe(ESCROW_CONTRACT);
    expect(typed.domain.chainId).toBe(BigInt(CHAIN_ID));
  });

  test('message contains all required fields', () => {
    const typed = buildMintApprovalTypedData({
      predictionHash,
      signer: PREDICTOR,
      collateral: PREDICTOR_COLLATERAL,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    });

    expect(typed.message.predictionHash).toBe(predictionHash);
    expect(typed.message.signer).toBe(PREDICTOR);
    expect(typed.message.collateral).toBe(PREDICTOR_COLLATERAL);
    expect(typed.message.nonce).toBe(NONCE);
    expect(typed.message.deadline).toBe(DEADLINE);
  });

  test('type fields match MINT_APPROVAL_TYPEHASH structure', () => {
    // These must match SignatureValidator.MINT_APPROVAL_TYPEHASH:
    // keccak256("MintApproval(bytes32 predictionHash,address signer,uint256 collateral,uint256 nonce,uint256 deadline)")
    const fieldNames = MINT_APPROVAL_TYPES.MintApproval.map((f) => f.name);
    expect(fieldNames).toEqual([
      'predictionHash',
      'signer',
      'collateral',
      'nonce',
      'deadline',
    ]);

    const fieldTypes = MINT_APPROVAL_TYPES.MintApproval.map((f) => f.type);
    expect(fieldTypes).toEqual([
      'bytes32',
      'address',
      'uint256',
      'uint256',
      'uint256',
    ]);
  });
});

// ============================================================================
// 5. Signer correctness — predictor vs counterparty
// ============================================================================

describe('signer assignment', () => {
  test('predictor mint uses predictor as signer', () => {
    const typed = buildPredictorMintTypedData({
      picks: PICKS,
      predictorCollateral: PREDICTOR_COLLATERAL,
      counterpartyCollateral: COUNTERPARTY_COLLATERAL,
      predictor: PREDICTOR,
      counterparty: COUNTERPARTY,
      predictorNonce: NONCE,
      predictorDeadline: DEADLINE,
      predictorSponsor: zeroAddress,
      predictorSponsorData: '0x',
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    });

    expect(typed.message.signer).toBe(PREDICTOR);
    expect(typed.message.collateral).toBe(PREDICTOR_COLLATERAL);
  });

  test('counterparty mint uses counterparty as signer (catches #117)', () => {
    const typed = buildCounterpartyMintTypedData({
      picks: PICKS,
      predictorCollateral: PREDICTOR_COLLATERAL,
      counterpartyCollateral: COUNTERPARTY_COLLATERAL,
      predictor: PREDICTOR,
      counterparty: COUNTERPARTY,
      counterpartyNonce: NONCE,
      counterpartyDeadline: DEADLINE,
      predictorSponsor: zeroAddress,
      predictorSponsorData: '0x',
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    });

    expect(typed.message.signer).toBe(COUNTERPARTY);
    expect(typed.message.collateral).toBe(COUNTERPARTY_COLLATERAL);
  });

  test('predictor and counterparty get the same predictionHash', () => {
    const predictorTyped = buildPredictorMintTypedData({
      picks: PICKS,
      predictorCollateral: PREDICTOR_COLLATERAL,
      counterpartyCollateral: COUNTERPARTY_COLLATERAL,
      predictor: PREDICTOR,
      counterparty: COUNTERPARTY,
      predictorNonce: NONCE,
      predictorDeadline: DEADLINE,
      predictorSponsor: zeroAddress,
      predictorSponsorData: '0x',
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    });

    const counterpartyTyped = buildCounterpartyMintTypedData({
      picks: PICKS,
      predictorCollateral: PREDICTOR_COLLATERAL,
      counterpartyCollateral: COUNTERPARTY_COLLATERAL,
      predictor: PREDICTOR,
      counterparty: COUNTERPARTY,
      counterpartyNonce: NONCE,
      counterpartyDeadline: DEADLINE,
      predictorSponsor: zeroAddress,
      predictorSponsorData: '0x',
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    });

    // Both sides must agree on the predictionHash
    expect(predictorTyped.message.predictionHash).toBe(
      counterpartyTyped.message.predictionHash
    );

    // But they sign with different signers
    expect(predictorTyped.message.signer).not.toBe(
      counterpartyTyped.message.signer
    );
  });
});

// ============================================================================
// 6. hashMintApproval — full EIP-712 hash stability
// ============================================================================

describe('hashMintApproval', () => {
  const predictionHash = computePredictionHash(
    computePickConfigId(PICKS),
    PREDICTOR_COLLATERAL,
    COUNTERPARTY_COLLATERAL,
    PREDICTOR,
    COUNTERPARTY,
    zeroAddress,
    '0x'
  );

  const params = {
    predictionHash,
    signer: PREDICTOR,
    collateral: PREDICTOR_COLLATERAL,
    nonce: NONCE,
    deadline: DEADLINE,
    verifyingContract: ESCROW_CONTRACT,
    chainId: CHAIN_ID,
  };

  test('matches viem hashTypedData computation', () => {
    const fromFunction = hashMintApproval(params);
    const fromViem = hashTypedData({
      domain: getEscrowDomain(ESCROW_CONTRACT, CHAIN_ID),
      types: MINT_APPROVAL_TYPES,
      primaryType: 'MintApproval',
      message: {
        predictionHash,
        signer: PREDICTOR,
        collateral: PREDICTOR_COLLATERAL,
        nonce: NONCE,
        deadline: DEADLINE,
      },
    });

    expect(fromFunction).toBe(fromViem);
  });

  test('different chain ID produces different hash', () => {
    const hash1 = hashMintApproval(params);
    const hash2 = hashMintApproval({ ...params, chainId: 42161 });
    expect(hash1).not.toBe(hash2);
  });

  test('different verifying contract produces different hash', () => {
    const hash1 = hashMintApproval(params);
    const hash2 = hashMintApproval({
      ...params,
      verifyingContract: getAddress(
        '0x5555555555555555555555555555555555555555'
      ),
    });
    expect(hash1).not.toBe(hash2);
  });
});

// ============================================================================
// 7. BurnApproval — structure validation
// ============================================================================

describe('BurnApproval', () => {
  test('type fields match BURN_APPROVAL_TYPEHASH structure', () => {
    const fieldNames = BURN_APPROVAL_TYPES.BurnApproval.map((f) => f.name);
    expect(fieldNames).toEqual([
      'burnHash',
      'signer',
      'tokenAmount',
      'payout',
      'nonce',
      'deadline',
    ]);

    const fieldTypes = BURN_APPROVAL_TYPES.BurnApproval.map((f) => f.type);
    expect(fieldTypes).toEqual([
      'bytes32',
      'address',
      'uint256',
      'uint256',
      'uint256',
      'uint256',
    ]);
  });

  test('hashBurnApproval matches viem hashTypedData', () => {
    const pickConfigId = computePickConfigId(PICKS);
    const burnHash = computeBurnHash(
      pickConfigId,
      500000n,
      500000n,
      PREDICTOR,
      COUNTERPARTY,
      1000000n,
      0n
    );

    const params = {
      burnHash,
      signer: PREDICTOR,
      tokenAmount: 500000n,
      payout: 1000000n,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    };

    const fromFunction = hashBurnApproval(params);
    const fromViem = hashTypedData({
      domain: getEscrowDomain(ESCROW_CONTRACT, CHAIN_ID),
      types: BURN_APPROVAL_TYPES,
      primaryType: 'BurnApproval',
      message: {
        burnHash,
        signer: PREDICTOR,
        tokenAmount: 500000n,
        payout: 1000000n,
        nonce: NONCE,
        deadline: DEADLINE,
      },
    });

    expect(fromFunction).toBe(fromViem);
  });
});

// ============================================================================
// 8. AuctionIntent — relayer-side auth
// ============================================================================

describe('buildAuctionIntentTypedData', () => {
  test('message contains all required fields', () => {
    const typed = buildAuctionIntentTypedData({
      picks: PICKS,
      predictor: PREDICTOR,
      predictorCollateral: PREDICTOR_COLLATERAL,
      predictorNonce: NONCE,
      predictorDeadline: DEADLINE,
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    });

    expect(typed.primaryType).toBe('AuctionIntent');
    expect(typed.message.predictor).toBe(PREDICTOR);
    expect(typed.message.predictorCollateral).toBe(PREDICTOR_COLLATERAL);
    expect(typed.message.predictorNonce).toBe(NONCE);
    expect(typed.message.predictorDeadline).toBe(DEADLINE);
    expect(typed.message.picks).toHaveLength(1);
    expect(typed.message.picks[0].predictedOutcome).toBe(1);
  });

  test('picks are properly structured in the message', () => {
    const typed = buildAuctionIntentTypedData({
      picks: TWO_PICKS,
      predictor: PREDICTOR,
      predictorCollateral: PREDICTOR_COLLATERAL,
      predictorNonce: NONCE,
      predictorDeadline: DEADLINE,
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    });

    expect(typed.message.picks).toHaveLength(2);
    expect(typed.message.picks[0].conditionResolver).toBe(
      TWO_PICKS[0].conditionResolver
    );
    expect(typed.message.picks[1].conditionResolver).toBe(
      TWO_PICKS[1].conditionResolver
    );
  });
});

// ============================================================================
// 9. predictionId — uniqueness per mint
// ============================================================================

describe('computePredictionId', () => {
  const pickConfigId = computePickConfigId(PICKS);

  test('different nonces produce different predictionId', () => {
    const id1 = computePredictionId(
      pickConfigId,
      PREDICTOR,
      COUNTERPARTY,
      1n,
      2n
    );
    const id2 = computePredictionId(
      pickConfigId,
      PREDICTOR,
      COUNTERPARTY,
      3n,
      2n
    );
    expect(id1).not.toBe(id2);
  });
});

// ============================================================================
// 10. Vault ERC-1271 double-wrap (catches #118)
//
// The vault's isValidSignature doesn't verify the raw MintApproval hash.
// It wraps it in Approve(messageHash, owner) using SignatureProcessor domain.
// Bug #118: vault signed the raw hash without the wrapper.
// Bug #117: vault used manager EOA as signer instead of vault contract address.
// ============================================================================

describe('vault ERC-1271 double-wrap signing', () => {
  const VAULT_ADDRESS = COUNTERPARTY; // vault is the counterparty
  const MANAGER_EOA = getAddress('0x6666666666666666666666666666666666666666');

  // SignatureProcessor domain (different from escrow domain!)
  const VAULT_APPROVE_TYPES = {
    Approve: [
      { name: 'messageHash', type: 'bytes32' },
      { name: 'owner', type: 'address' },
    ],
  } as const;

  function getVaultDomain(vaultAddress: Address, chainId: number) {
    return {
      name: 'SignatureProcessor' as const,
      version: '1' as const,
      chainId: BigInt(chainId),
      verifyingContract: vaultAddress,
    };
  }

  const predictionHash = computePredictionHash(
    computePickConfigId(PICKS),
    PREDICTOR_COLLATERAL,
    COUNTERPARTY_COLLATERAL,
    PREDICTOR,
    VAULT_ADDRESS,
    zeroAddress,
    '0x'
  );

  // Step 1: MintApproval hash (escrow domain, signer = vault contract)
  const mintApprovalHash = hashMintApproval({
    predictionHash,
    signer: VAULT_ADDRESS, // vault contract, NOT manager EOA
    collateral: COUNTERPARTY_COLLATERAL,
    nonce: NONCE,
    deadline: DEADLINE,
    verifyingContract: ESCROW_CONTRACT,
    chainId: CHAIN_ID,
  });

  test('MintApproval signer must be vault contract, not manager EOA (catches #117)', () => {
    const withManager = hashMintApproval({
      predictionHash,
      signer: MANAGER_EOA, // WRONG
      collateral: COUNTERPARTY_COLLATERAL,
      nonce: NONCE,
      deadline: DEADLINE,
      verifyingContract: ESCROW_CONTRACT,
      chainId: CHAIN_ID,
    });

    expect(mintApprovalHash).not.toBe(withManager);
  });

  test('Approve wrapper uses SignatureProcessor domain, not escrow domain (catches #118)', () => {
    const withVaultDomain = hashTypedData({
      domain: getVaultDomain(VAULT_ADDRESS, CHAIN_ID),
      types: VAULT_APPROVE_TYPES,
      primaryType: 'Approve',
      message: { messageHash: mintApprovalHash, owner: MANAGER_EOA },
    });

    const withEscrowDomain = hashTypedData({
      domain: getEscrowDomain(ESCROW_CONTRACT, CHAIN_ID),
      types: VAULT_APPROVE_TYPES,
      primaryType: 'Approve',
      message: { messageHash: mintApprovalHash, owner: MANAGER_EOA },
    });

    // Using escrow domain instead of vault domain was the #118 bug
    expect(withVaultDomain).not.toBe(withEscrowDomain);
  });

  test('Approve verifyingContract is the vault address', () => {
    const domain = getVaultDomain(VAULT_ADDRESS, CHAIN_ID);
    expect(domain.name).toBe('SignatureProcessor');
    expect(domain.version).toBe('1');
    expect(domain.verifyingContract).toBe(VAULT_ADDRESS);
  });

  test('Approve owner is manager EOA, not vault contract', () => {
    const withManager = hashTypedData({
      domain: getVaultDomain(VAULT_ADDRESS, CHAIN_ID),
      types: VAULT_APPROVE_TYPES,
      primaryType: 'Approve',
      message: { messageHash: mintApprovalHash, owner: MANAGER_EOA },
    });

    const withVault = hashTypedData({
      domain: getVaultDomain(VAULT_ADDRESS, CHAIN_ID),
      types: VAULT_APPROVE_TYPES,
      primaryType: 'Approve',
      message: { messageHash: mintApprovalHash, owner: VAULT_ADDRESS },
    });

    expect(withManager).not.toBe(withVault);
  });

  test('Approve typehash matches SignatureProcessor.APPROVE_TYPEHASH', () => {
    // keccak256("Approve(bytes32 messageHash,address owner)")
    const typehash = keccak256(
      toHex('Approve(bytes32 messageHash,address owner)')
    );
    // Pulled from Forge fixture — SignatureProcessor.APPROVE_TYPEHASH
    expect(typehash).toBe(goldenHashes.approveTypehash);
  });
});
