-- AlterTable
ALTER TABLE "cache_candle" ALTER COLUMN "sumUsed" SET DATA TYPE VARCHAR,
ALTER COLUMN "sumFeePaid" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "resource_price" ALTER COLUMN "value" SET DATA TYPE VARCHAR,
ALTER COLUMN "used" SET DATA TYPE VARCHAR,
ALTER COLUMN "feePaid" SET DATA TYPE VARCHAR;
