-- AlterTable
ALTER TABLE "attestation" ALTER COLUMN "questionId" DROP DEFAULT;

-- AlterTable
ALTER TABLE "position" ALTER COLUMN "lpBaseToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "lpQuoteToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "baseToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "quoteToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "borrowedBaseToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "borrowedQuoteToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "collateral" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "transaction" ALTER COLUMN "tradeRatioD18" SET DATA TYPE VARCHAR,
ALTER COLUMN "baseToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "quoteToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "borrowedBaseToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "borrowedQuoteToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "collateral" SET DATA TYPE VARCHAR,
ALTER COLUMN "lpBaseDeltaToken" SET DATA TYPE VARCHAR,
ALTER COLUMN "lpQuoteDeltaToken" SET DATA TYPE VARCHAR;
