import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildClientSchema, type IntrospectionQuery } from 'graphql';
import { introspect } from './testApollo';

const apiRoot = resolve(fileURLToPath(import.meta.url), '..', '..', '..');

/**
 * Reads the committed schema.graphql. This file is regenerated by
 * `pnpm --filter @sapience/api run emit-schema` (wired into CI's drift
 * check). Tests that need the SDL read this rather than rebuilding the
 * schema in-process — type-graphql's decorator metadata only works under
 * tsx/tsc, not under Vite's default transform pipeline.
 */
export const readCommittedSchema = async (): Promise<string> => {
  return readFile(resolve(apiRoot, 'schema.graphql'), 'utf8');
};

/**
 * Live introspection of the running test server. Use this when a test
 * cares about what the server actually exposes (e.g. introspection
 * snapshot), not just what the committed SDL says.
 */
export const getRuntimeSchema = async () => {
  const data = (await introspect()) as IntrospectionQuery;
  return buildClientSchema(data);
};
